GET https://serene-retreat-74102.herokuapp.com/api/persons

###
GET https://serene-retreat-74102.herokuapp.com/api/persons/1

###
GET https://serene-retreat-74102.herokuapp.com/api/persons/api/persons/5

###
DELETE https://serene-retreat-74102.herokuapp.com/api/persons/2

###
POST https://serene-retreat-74102.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Emily Bash",
  "number": "159-753-8462"
}